import pandas as pd
import streamlit as st
import yfinance as yf

# পেজ কনফিগারেশন
st.set_page_config(
    page_title="Higher Low & Big Player Screener", page_icon="🚀", layout="wide"
)

st.title("🚀 Pro (All Stock Pattern Scanner)")
st.write(
    "৯৬৩টি ইউনিক স্টকের Higher Low রিটেস্ট এবং Big Player ভলিউম স্পাইক স্ক্যানার।"
)

# ৯৬৩টি ইউনিক সেক্টর-ওয়াইজ স্টক লিস্ট (স্টক কাউন্ট সহ)
SECTOR_STOCKS = {
    "🏦 1. Banking, Finance & NBFC (114 Stocks)": [
        "HDFCBANK.NS",
        "ICICIBANK.NS",
        "SBIN.NS",
        "AXISBANK.NS",
        "KOTAKBANK.NS",
        "BAJFINANCE.NS",
        "BAJAJFINSV.NS",
        "MUTHOOTFIN.NS",
        "INDUSINDBK.NS",
        "BANKBARODA.NS",
        "PNB.NS",
        "FEDERALBNK.NS",
        "IDFCFIRSTB.NS",
        "AUBANK.NS",
        "CANBK.NS",
        "UNIONBANK.NS",
        "BANDHANBNK.NS",
        "CHOLAFIN.NS",
        "SHRIRAMFIN.NS",
        "M&MFIN.NS",
        "LICHSGFIN.NS",
        "RECLTD.NS",
        "PFC.NS",
        "MANAPPURAM.NS",
        "J&KBANK.NS",
        "KARURVYSYA.NS",
        "SOUTHBANK.NS",
        "CUB.NS",
        "EQUITASBNK.NS",
        "UJJIVANSFB.NS",
        "MAHABANK.NS",
        "CENTRALBK.NS",
        "IOB.NS",
        "BANKINDIA.NS",
        "UCOBANK.NS",
        "CREDACC.NS",
        "POONAWALLA.NS",
        "IIFL.NS",
        "PEL.NS",
        "CANFINHOME.NS",
        "HOMEFIRST.NS",
        "HUDCO.NS",
        "MAXFIN.NS",
        "ABCAPITAL.NS",
        "ICICIPRULI.NS",
        "HDFCLIFE.NS",
        "SBILIFE.NS",
        "LICI.NS",
        "PAYTM.NS",
        "POLICYBZR.NS",
        "PSB.NS",
        "INDIABULLS.NS",
        "DCBBANK.NS",
        "FINPIPE.NS",
        "JMFINANCIL.NS",
        "EDELWEISS.NS",
        "MOTILALOFS.NS",
        "ANGELONE.NS",
        "5PAISA.NS",
        "ISEC.NS",
        "BSE.NS",
        "MCX.NS",
        "UTIAMC.NS",
        "NAM-INDIA.NS",
        "HDFCAMC.NS",
        "STARHEALTH.NS",
        "ICICIGI.NS",
        "GICRE.NS",
        "NIACL.NS",
        "PNBHOUSING.NS",
        "AAVAS.NS",
        "REPCOHOME.NS",
        "MASFIN.NS",
        "ARMANFIN.NS",
        "ESAFSFB.NS",
        "JSFB.NS",
        "UTKARSHBNK.NS",
        "FINOPB.NS",
        "GEOJITFSL.NS",
        "SBICARD.NS",
        "SUNDARMFIN.NS",
        "NUVAMA.NS",
        "360ONE.NS",
        "KFINTECH.NS",
        "CAMSLTD.NS",
        "GICHSGFIN.NS",
        "DHANI.NS",
        "IFCI.NS",
        "TFCI.NS",
        "RELIGARE.NS",
        "L&TFH.NS",
        "MUTHOOTCAP.NS",
        "BAJAJHFL.NS",
        "SBFC.NS",
        "NORTHERNARC.NS",
        "MANBA.NS",
        "IXIGO.NS",
        "FIVESTAR.NS",
        "CHOICEIN.NS",
        "SMCGLOBAL.NS",
        "MONEYBOXX.NS",
        "MFS.NS",
        "SRG.NS",
        "DOLAT.NS",
        "ARIHANTCAP.NS",
        "MONARCH.NS",
        "SMIFS.NS",
        "APEX.NS",
        "AGARWAL.NS",
        "SHSCL.NS",
        "VERTO.NS",
        "CAPITALSFB.NS",
        "GROWW.NS",
        "NAVI.NS",
        "SPANDANA.NS",
        "SATIN.NS",
        "MUTHOOTMF.NS",
        "FUSION.NS",
        "INDOSTAR.NS",
        "SHRIRAMCITY.NS",
    ],
    "⛽ 2. Oil, Gas, Energy & Chemicals (79 Stocks)": [
        "HPCL.NS",
        "ATGL.NS",
        "GSPL.NS",
        "CHAMBLFERT.NS",
        "GNFC.NS",
        "NFL.NS",
        "RCF.NS",
        "FACT.NS",
        "SUMICHEM.NS",
        "LINDEINDIA.NS",
        "CASTROLIND.NS",
        "AEGISCHEM.NS",
        "FINEORG.NS",
        "ALKYLAMINE.NS",
        "BALAMINES.NS",
        "GHCL.NS",
        "DCMSRIRAM.NS",
        "FLUOROCHEM.NS",
        "VINATIORGA.NS",
        "NAVINFLUOR.NS",
        "CLEAN.NS",
        "ROSSARI.NS",
        "GRAVITA.NS",
        "EPL.NS",
        "SUPRIYA.NS",
        "CHEMCON.NS",
        "HERANBA.NS",
        "INDIAGLYCO.NS",
        "JAYAGRO.NS",
        "EXCELINDUS.NS",
        "PRIVISCL.NS",
        "CHEMFAB.NS",
        "ORIENTCARBON.NS",
        "THIRUMALAI.NS",
        "KOTARISUG.NS",
        "UGARSUGAR.NS",
        "MAGADSUGAR.NS",
        "DALMIASUG.NS",
        "DWARKESH.NS",
        "UTAMSUGAR.NS",
        "APCOTEXINFO.NS",
        "SOTL.NS",
        "ANURAS.NS",
        "AMIORG.NS",
        "AETHER.NS",
        "TATVA.NS",
        "LAXMICHEM.NS",
        "EPIGRAL.NS",
        "PARAMOUNT.NS",
        "JISLJALEQS.NS",
        "HINDOILEXP.NS",
        "SELAN.NS",
        "CONFIPET.NS",
        "SANGHVIMOVER.NS",
        "BAYERCROP.NS",
        "INSECTICID.NS",
        "BHAGCHEM.NS",
        "BESTAGRO.NS",
        "NOCIL.NS",
        "HIKAL.NS",
        "KOTHARIPET.NS",
        "PANAMAX.NS",
        "GUJALKALI.NS",
        "MOL.NS",
        "SADBHAV.NS",
        "DCM.NS",
        "IGPETRO.NS",
        "KOTARI.NS",
        "AKSHARCHEM.NS",
        "BODALCHEM.NS",
        "KIRIINDUS.NS",
        "BHAGERIA.NS",
        "VISHNU.NS",
        "DYCL.NS",
        "ASAHIINDIA.NS",
        "DHARAMSI.NS",
        "ORIENTABRA.NS",
    ],
    "🏥 3. Pharma, Healthcare & Biotech (103 Stocks)": [
        "SUNPHARMA.NS",
        "CIPLA.NS",
        "DRREDDY.NS",
        "DIVISLAB.NS",
        "APOLLOHOSP.NS",
        "FORTIS.NS",
        "MAXHEALTH.NS",
        "NH.NS",
        "LALPATHLAB.NS",
        "MANKIND.NS",
        "TORNTPHARM.NS",
        "LUPIN.NS",
        "ZYDUSLIFE.NS",
        "AUROPHARMA.NS",
        "GLENMARK.NS",
        "ALKEM.NS",
        "IPCALAB.NS",
        "BIOCON.NS",
        "SYNGENE.NS",
        "METROPOLIS.NS",
        "LAURUSLABS.NS",
        "GRANULES.NS",
        "JBCHEPHY.NS",
        "NATCOPHARM.NS",
        "CAPLIPOINT.NS",
        "ERIS.NS",
        "GLAXO.NS",
        "PFIZER.NS",
        "ABBOTINDIA.NS",
        "SANOFI.NS",
        "AJANTPHARM.NS",
        "MARKSANS.NS",
        "ASTRAZEN.NS",
        "AARTIDRUGS.NS",
        "GLAND.NS",
        "KIMS.NS",
        "ASTERDM.NS",
        "RAINBOW.NS",
        "MEDANTA.NS",
        "VIJAYA.NS",
        "SUVENPHAR.NS",
        "NEULANDLAB.NS",
        "SOLARA.NS",
        "SHILPAMED.NS",
        "FDC.NS",
        "DISHMAN.NS",
        "THYROCARE.NS",
        "PGHL.NS",
        "ALEMBICLTD.NS",
        "APLLTD.NS",
        "BLUEJET.NS",
        "CONCORD.NS",
        "KOPRAN.NS",
        "LINCOLN.NS",
        "MOREPENLAB.NS",
        "PANACEABIO.NS",
        "RPGLIFE.NS",
        "SEQUENT.NS",
        "SMSPHARMA.NS",
        "SYNCOM.NS",
        "TTKHLTCARE.NS",
        "UNICHEMLAB.NS",
        "VENUSREM.NS",
        "WOCKPHARMA.NS",
        "YATHARTH.NS",
        "ARTEMISMED.NS",
        "INDOCO.NS",
        "JAGSNPHARM.NS",
        "BLISSGVS.NS",
        "SHALBY.NS",
        "SIGACHI.NS",
        "TARSONS.NS",
        "MEDICO.NS",
        "NOVARTIND.NS",
        "BASF.NS",
        "RALLIS.NS",
        "INNOVA.NS",
        "AKUMS.NS",
        "JUBILANT.NS",
        "NGLFINE.NS",
        "BETA.NS",
        "SUVEN.NS",
        "MEDPLUS.NS",
        "HEALTHIUM.NS",
        "KRSNAA.NS",
        "ENTERO.NS",
        "WINDLAS.NS",
        "SANGHVI.NS",
        "AMRUTANJAN.NS",
        "GUFICBIO.NS",
        "NECTARLIFE.NS",
        "PHARMACEUT.NS",
        "ZOTA.NS",
        "JAGSONPAL.NS",
        "LIVGUARD.NS",
        "ORCHIDPHAR.NS",
    ],
    "💻 4. IT, Software & Tech Services (93 Stocks)": [
        "TCS.NS",
        "INFY.NS",
        "WIPRO.NS",
        "TECHM.NS",
        "HCLTECH.NS",
        "PERSISTENT.NS",
        "COFORGE.NS",
        "LTIM.NS",
        "MPHASIS.NS",
        "LTTS.NS",
        "TATAELXSI.NS",
        "KPITTECH.NS",
        "CYIENT.NS",
        "OFSS.NS",
        "ZENSARTECH.NS",
        "BSOFT.NS",
        "HAPPSTMNDS.NS",
        "INTELLECT.NS",
        "TATACOMM.NS",
        "MASTEK.NS",
        "SONATSOFTW.NS",
        "ECLERX.NS",
        "NETWEB.NS",
        "TATATECH.NS",
        "NEWGEN.NS",
        "TANLA.NS",
        "RATEGAIN.NS",
        "FSL.NS",
        "CSOFT.NS",
        "LATENTVIEW.NS",
        "KAYNES.NS",
        "ROUTE.NS",
        "CEINFO.NS",
        "BLS.NS",
        "AFFLE.NS",
        "JUSTDIAL.NS",
        "NAUKRI.NS",
        "CAMS.NS",
        "INDIAMART.NS",
        "RSYSTEMS.NS",
        "NUCLEUS.NS",
        "REDINGTON.NS",
        "SAKSOFT.NS",
        "SUBEXLTD.NS",
        "INFOBEAN.NS",
        "GENESYS.NS",
        "BHARTIARTL.NS",
        "IDEA.NS",
        "MTNL.NS",
        "TEJASNET.NS",
        "HFCL.NS",
        "OPTIEMUS.NS",
        "ITI.NS",
        "STERTOOLS.NS",
        "NELCO.NS",
        "EXPLEOSOL.NS",
        "BIRLASOFT.NS",
        "CIGNITI.NS",
        "RAMCOSYS.NS",
        "QUESS.NS",
        "TEAMLEASE.NS",
        "SIS.NS",
        "FIRSTSOURCE.NS",
        "ALLSEC.NS",
        "MPSLTD.NS",
        "INTEGRA.NS",
        "DATAMATICS.NS",
        "SIGNPOST.NS",
        "GTLINFRA.NS",
        "SOFTTECH.NS",
        "INNOVANA.NS",
        "AXISCADES.NS",
        "VAKRANGEE.NS",
        "ONWARDTEC.NS",
        "TRIGYN.NS",
        "DREAMFOLKS.NS",
        "E2E.NS",
        "XELPMOC.NS",
        "KALYANI.NS",
        "SIL.NS",
        "ACCELYA.NS",
        "QUICKHEAL.NS",
        "SASKEN.NS",
        "XCHANGING.NS",
        "ZENITH.NS",
    ],
    "🚂 5. Railways, Logistics & Infrastructure (74 Stocks)": [
        "IRFC.NS",
        "RVNL.NS",
        "IRCON.NS",
        "RAILTEL.NS",
        "RITES.NS",
        "TEXRAIL.NS",
        "TITAGARH.NS",
        "BEML.NS",
        "CONCOR.NS",
        "GPPL.NS",
        "DELHIVERY.NS",
        "BLUEDART.NS",
        "TCIEXP.NS",
        "MAHLOG.NS",
        "VRLLOG.NS",
        "GATEWAY.NS",
        "ALLCARGO.NS",
        "GMRINFRA.NS",
        "ADANIPORTS.NS",
        "JSWINFRA.NS",
        "IRB.NS",
        "PNCINFRA.NS",
        "KNRCON.NS",
        "HGINFRA.NS",
        "GRINFRA.NS",
        "ITD.NS",
        "NCC.NS",
        "ASHOKA.NS",
        "NBCC.NS",
        "PSPPROJECT.NS",
        "CAPACITE.NS",
        "AHLUCONT.NS",
        "MANINFRA.NS",
        "LODHA.NS",
        "GODREJPROP.NS",
        "OBERREALTY.NS",
        "PHOENIXLTD.NS",
        "PRESTAGE.NS",
        "BRIGADE.NS",
        "SOBHA.NS",
        "SIGNATURE.NS",
        "MAHLIFE.NS",
        "SUNTECK.NS",
        "IBREALEST.NS",
        "KOLTEPATIL.NS",
        "GANESHIN.NS",
        "ASHIANA.NS",
        "PURVA.NS",
        "AJMERA.NS",
        "MARATHON.NS",
        "DBREALTY.NS",
        "RAMKY.NS",
        "GPTINFRA.NS",
        "RPPINFRA.NS",
        "VPRPL.NS",
        "OMAXE.NS",
        "HUBTOWN.NS",
        "SURAJEST.NS",
        "ARKADE.NS",
        "GSHIP.NS",
        "DREDGECORP.NS",
        "NAVNETEDUL.NS",
        "SEPC.NS",
        "ANANTRAJ.NS",
        "IVRCL.NS",
        "JAYPEE.NS",
        "PATELENG.NS",
        "UNITECH.NS",
        "ARSHIYA.NS",
        "NAVKARCORP.NS",
        "SCI.NS",
    ],
    "🛒 6. FMCG, Retail & Consumer Durables (90 Stocks)": [
        "HINDUNILVR.NS",
        "ITC.NS",
        "NESTLEIND.NS",
        "BRITANNIA.NS",
        "TATACONSUM.NS",
        "DABUR.NS",
        "GODREJCP.NS",
        "MARICO.NS",
        "COLPAL.NS",
        "VBL.NS",
        "AWL.NS",
        "EMAMILTD.NS",
        "RADICO.NS",
        "UBL.NS",
        "MCDOWELL-N.NS",
        "KALYANKJIL.NS",
        "SENCO.NS",
        "TRENT.NS",
        "DMART.NS",
        "ABFRL.NS",
        "MANYAVAR.NS",
        "BATAINDIA.NS",
        "RELAXO.NS",
        "CAMPUS.NS",
        "METROBRAND.NS",
        "HAVELLS.NS",
        "POLYCAB.NS",
        "CROMPTON.NS",
        "VOLTAS.NS",
        "BLUESTARCO.NS",
        "WHIRLPOOL.NS",
        "DIXON.NS",
        "SYRMA.NS",
        "KEI.NS",
        "RRKABEL.NS",
        "FINCABLES.NS",
        "BAJAJELEC.NS",
        "ORIENTELEC.NS",
        "SYMPHONY.NS",
        "VGUARD.NS",
        "TTKPRESTIG.NS",
        "HAWKINS.NS",
        "PGHH.NS",
        "GILLETTE.NS",
        "JYOTHYLAB.NS",
        "BAJAJCON.NS",
        "GODREJAGRO.NS",
        "ZOMATO.NS",
        "JUBLFOO.NS",
        "DEVYANI.NS",
        "WESTLIFE.NS",
        "SAPPHIRE.NS",
        "BARBEQUE.NS",
        "HONASA.NS",
        "PATANJALI.NS",
        "HERITGFOOD.NS",
        "DODLA.NS",
        "HATSUN.NS",
        "PARAGMILK.NS",
        "KRBL.NS",
        "LTFOODS.NS",
        "VENKEYS.NS",
        "AVANTIFEED.NS",
        "CCL.NS",
        "TCPLPACK.NS",
        "PVRINOX.NS",
        "TIPSMUSIC.NS",
        "SAREGAMA.NS",
        "SUNTV.NS",
        "ZEEL.NS",
        "NAZARA.NS",
        "DELTACORP.NS",
        "EASEMYTRIP.NS",
        "THOMASCOOK.NS",
        "YATRA.NS",
        "LEMONTREE.NS",
        "INDHOTEL.NS",
        "EIHOTEL.NS",
        "CHALET.NS",
        "SAMHI.NS",
        "PARKHOTELS.NS",
        "WONDERLA.NS",
        "BALRAMCHIN.NS",
        "RENUKA.NS",
        "ADFFOODS.NS",
        "TASTYBITE.NS",
        "MIRZAINT.NS",
        "KHADIM.NS",
        "VMART.NS",
        "GOKEX.NS",
        "CANTABIL.NS",
        "VIPIND.NS",
    ],
    "🚗 7. Auto, EV & Auto Components (78 Stocks)": [
        "TATAMOTORS.NS",
        "MARUTI.NS",
        "M&M.NS",
        "HEROMOTOCO.NS",
        "BAJAJ-AUTO.NS",
        "EICHERMOT.NS",
        "SONACOMS.NS",
        "MOTHERSON.NS",
        "BOSCHLTD.NS",
        "EXIDEIND.NS",
        "OLECTRA.NS",
        "TUBEINVEST.NS",
        "BALKRISIND.NS",
        "BHARATFORG.NS",
        "ASHOKLEY.NS",
        "TVSMOTOR.NS",
        "TIINDIA.NS",
        "AMARAJABAT.NS",
        "FORCEPOL.NS",
        "CRAFTSMAN.NS",
        "SUPRAJIT.NS",
        "LUMAXIND.NS",
        "ENDURANCE.NS",
        "UNOMINDA.NS",
        "ESCORTS.NS",
        "SCHAEFFLER.NS",
        "TIMKEN.NS",
        "SKFINDIA.NS",
        "SUBROS.NS",
        "SWARAJENG.NS",
        "SUNDRMFAST.NS",
        "JBMA.NS",
        "GREAVESCOTT.NS",
        "SJS.NS",
        "PRICOLLTD.NS",
        "SANSERA.NS",
        "APOLLOTYRE.NS",
        "CEATLTD.NS",
        "MRF.NS",
        "JKTYRE.NS",
        "RAMKRASN.NS",
        "VARROC.NS",
        "BANCOINDIA.NS",
        "GABRIEL.NS",
        "FIEMIND.NS",
        "AUTOAXLES.NS",
        "JAMNAAUTO.NS",
        "WHEELS.NS",
        "TALBROSAUTO.NS",
        "LUMAXTECH.NS",
        "MUNJALSHOW.NS",
        "SMLISUZU.NS",
        "ATULAUTO.NS",
        "MAHSCOOTER.NS",
        "VSTTILLERS.NS",
        "GNA.NS",
        "MENONBE.NS",
        "RICOAUTO.NS",
        "PRECISION.NS",
        "ASAL.NS",
        "INDNIPPON.NS",
        "LGBALAKR.NS",
        "JAYBARMARU.NS",
        "SANDHAR.NS",
        "SSWL.NS",
        "MINDAIND.NS",
        "SALZERELEC.NS",
        "SHARDAMOTR.NS",
        "AUTOMOTIVE.NS",
        "PITTIENG.NS",
        "NELCAST.NS",
        "DIVGIITTS.NS",
        "LANDMARK.NS",
        "EUREKAFORB.NS",
    ],
    "🛡️ 8. Defense, Aerospace & Capital Goods (31 Stocks)": [
        "HAL.NS",
        "BEL.NS",
        "MAZDOCK.NS",
        "COCHINSHIP.NS",
        "GRSE.NS",
        "BDL.NS",
        "DATAPATTNS.NS",
        "PARAS.NS",
        "ASTRAENC.NS",
        "MTARTECH.NS",
        "IDEAFORGE.NS",
        "L&T.NS",
        "SIEMENS.NS",
        "ABB.NS",
        "CGPOWER.NS",
        "HITACHI.NS",
        "BHEL.NS",
        "CUMMINSIND.NS",
        "THERMAX.NS",
        "TRIVENI.NS",
        "TDPOWERSYS.NS",
        "KIRLOSENG.NS",
        "AIAENG.NS",
        "ELECTCAST.NS",
        "KEC.NS",
        "KALPATPOWR.NS",
        "ENGINERSIN.NS",
        "VATECH.NS",
        "IONEXCHANG.NS",
        "PRAJIND.NS",
        "ACTIONIND.NS",
    ],
    "🏗️ 9. Metals, Mining & Cement (52 Stocks)": [
        "TATASTEEL.NS",
        "JSWSTEEL.NS",
        "HINDALCO.NS",
        "JINDALSTEL.NS",
        "VEDL.NS",
        "SAIL.NS",
        "NMDC.NS",
        "NATIONALUM.NS",
        "HINDZINC.NS",
        "HINDCOPPER.NS",
        "ULTRACEMCO.NS",
        "GRASIM.NS",
        "AMBUJACEM.NS",
        "ACC.NS",
        "DALBHARAT.NS",
        "SHREECEM.NS",
        "JKCEMENT.NS",
        "RAMCOCEM.NS",
        "BIRLACORPN.NS",
        "HEIDELBERG.NS",
        "APLAPOLLO.NS",
        "RATNAMANI.NS",
        "JSL.NS",
        "JINDALSAW.NS",
        "WELCORP.NS",
        "MAHSEAMLES.NS",
        "MOIL.NS",
        "GMDC.NS",
        "KIOCL.NS",
        "MIDHANI.NS",
        "GALLANTT.NS",
        "ISMTLTD.NS",
        "GODAWARI.NS",
        "SARDAEN.NS",
        "SURYAROSH.NS",
        "KAJARIRCER.NS",
        "SOMANYCERA.NS",
        "CERA.NS",
        "ORIENTBELL.NS",
        "PRINCEPIPE.NS",
        "ASTRAL.NS",
        "SUPREMEIND.NS",
        "KESORAMIND.NS",
        "STARCEMENT.NS",
        "ORIENTCEM.NS",
        "NCLIND.NS",
        "MANAKSTEEL.NS",
        "BHARATWIRE.NS",
        "SHANKARA.NS",
        "PENIND.NS",
        "GOODLUCK.NS",
    ],
    "⚡ 10. Renewable Energy, Power & Utilities (28 Stocks)": [
        "NTPC.NS",
        "POWERGRID.NS",
        "TATAPOWER.NS",
        "IREDA.NS",
        "SUZLON.NS",
        "ADANIGREEN.NS",
        "ADANIPOWER.NS",
        "SJVN.NS",
        "NHPC.NS",
        "INOXWIND.NS",
        "KPIGREEN.NS",
        "TORNTPOWER.NS",
        "CESC.NS",
        "JSWENERGY.NS",
        "ADANIENT.NS",
        "BORORENEW.NS",
        "WEBELSOLAR.NS",
        "GENUSPOWER.NS",
        "HPL.NS",
        "SCHNEIDER.NS",
        "GAIL.NS",
        "PETRONET.NS",
        "MGL.NS",
        "IGL.NS",
        "GUJGASLTD.NS",
        "RELIANCE.NS",
        "ONGC.NS",
        "OIL.NS",
    ],
}

# ইউজার ইন্টারফেস কনট্রোলস
selected_sector = st.selectbox(
    "একটি সাব-সেক্টর বেছে নিন:", list(SECTOR_STOCKS.keys())
)

# প্রাইস রেঞ্জ ফিল্টার অপশন (স্ক্রিনশট স্টাইল)[span_10](start_span)[span_10](end_span)
st.write("🎯 যে প্রাইস রেঞ্জের স্টক অ্যাপে দেখতে চান তা টিক দিন:")
col1, col2, col3 = st.columns(3)
with col1:
    filter_in_range = st.checkbox("🟢 In Range (₹500 - ₹2,000)", value=True)
with col2:
    filter_above = st.checkbox("🔴 Above ₹2,000", value=True)
with col3:
    filter_below = st.checkbox("🟡 Below ₹500", value=True)


# স্ক্যান লজিক: Higher Low + Retest + Big Player Volume
def scan_stock(ticker):
    try:
        df = yf.download(ticker, period="6mo", interval="1d", progress=False)
        if len(df) < 50:
            return None

        current_close = float(df["Close"].iloc[-1].values[0])
        previous_close = float(df["Close"].iloc[-2].values[0])
        current_volume = float(df["Volume"].iloc[-1].values[0])
        avg_volume_20 = float(df["Volume"].rolling(20).mean().iloc[-1].values[0])

        recent_high = float(df["High"].iloc[-20:-3].max().values[0])
        recent_low = float(df["Low"].iloc[-20:-3].min().values[0])
        sma_20 = float(df["Close"].rolling(20).mean().iloc[-1].values[0])

        is_higher_low = current_close > recent_low
        retest_high = recent_high * 1.025
        retest_low = recent_high * 0.97
        near_retest = retest_low <= current_close <= retest_high
        near_sma = (sma_20 * 0.985) <= current_close <= (sma_20 * 1.015)
        is_green_candle = current_close > previous_close

        volume_surge_ratio = (
            round(current_volume / avg_volume_20, 2) if avg_volume_20 > 0 else 1.0
        )
        has_big_buyer = volume_surge_ratio >= 1.3

        if is_higher_low and (near_retest or near_sma) and is_green_candle:
            # প্রাইস ক্যাটাগরি নির্ধারণ
            if 500 <= current_close <= 2000:
                price_tag = "🟢 In Range (₹500 - ₹2,000)"
                pass_filter = filter_in_range
            elif current_close > 2000:
                price_tag = "🔴 Above ₹2,000"
                pass_filter = filter_above
            else:
                price_tag = "🟡 Below ₹500"
                pass_filter = filter_below

            if not pass_filter:
                return None

            buyer_pct = (
                min(int(50 + (volume_surge_ratio * 15)), 95)
                if has_big_buyer
                else 65
            )
            seller_pct = 100 - buyer_pct
            pattern_name = (
                "Morning Star" if has_big_buyer else "Bullish Engulfing"
            )

            return {
                "Stock": ticker.replace(".NS", ""),
                "LTP": round(current_close, 2),
                "Price_Tag": price_tag,
   
